sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly

install:
  - phpize
  - ./configure --enable-phk
  - make install

script: NO_INTERACTION=y make test
