
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind

install: phpize && ./configure --enable-phk && make install

# Xdebug versions < 2.3.3 caus PHP to crash when enabled with PHK ext

before_script:
  - phpenv config-rm xdebug.ini

# -m : test using valgrind
# -q : No interaction

script: sh travis/run-test.sh
